
import time
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get("https://opensource-demo.orangehrmlive.com/")
login = driver.find_element_by_css_selector("input[name='txtUsername']")
login.send_keys("Admin")
password = driver.find_element_by_name("txtPassword")
password.send_keys("admin123")
login_btn = driver.find_element_by_css_selector(".button")
login_btn.click()
pim = driver.find_element_by_id("menu_pim_viewPimModule")
pim.click()
time.sleep(3)
employeelist = driver.find_element_by_id("menu_pim_viewEmployeeList")
employeelist.click()
time.sleep(3)
employeename= driver.find_element_by_name("empsearch[employee_name][empName]")
employeename.send_keys("Иван Иванов")
employeename.click()
search = driver.find_element_by_xpath("//input[@id='searchBtn']")
search.click()
checkbox = driver.find_element_by_name("chkSelectRow[]")
checkbox.click()
delete = driver.find_element_by_name("btnDelete")
delete.click()
ok = driver.find_element_by_xpath("//input[@id='dialogDeleteBtn']")
time.sleep(3)
ok.click()
driver.quit()
